name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.GK_DOCKER_NAME }}
        run: sudo docker pull $DOCKER_USER/bike_fastapi:latest4
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f bike_fastapi_container1 || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.GK_DOCKER_NAME }}
        run: sudo docker run -it -d -p 8001:8001 --name bike_fastapi_container1 $DOCKER_USER/bike_fastapi:latest4
